version: '3'

services:
    web:
        container_name: twitgallery_web
        build: './web'
        depends_on:
            - db
        ports:
            - 1024:80
        volumes:
            - 'c:\dev\twitgallery\web\nginx:/etc/nginx'
            - 'c:\dev\twitgallery\web\www:/usr/share/nginx/html'
        restart: always
    app:
        container_name: twitgallery_app
        build: './app'
        depends_on:
            - db
        ports 5000:5000
        volumes:
            - 'c:\dev\twitgallery\app\src:/usr/src/app'
        env_file: app.env
        restart: always
    db:
        container_name: twitgallery_db
        environment:
            - POSTGRES_USER=tg_user
            - POSTGRES_PASSWORD=docker
            - POSTGRES_DB=twitgallery
        build: './db'
        restart: always

